name: stocks
functions:
- url: code/01-read-stocks.yaml
  name: stocks_reader
  kind: nuclio
- url: code/02-read-news.yaml
  name: news_reader
  kind: nuclio
- url: code/03-stream-viewer.yaml
  name: stream_viewer
  kind: nuclio
- url: code/04-grafana.yaml
  name: grafana
  kind: job
- url: training/bert_sentiment_classification.yaml
  name: bert_sentiment_classifier_trainer
  kind: job
- url: hub://sentiment_analysis_serving
  name: sentiment_analysis_server
workflows:
- name: main
  path: /User/demo-stocks/code/workflow.py
artifacts: []
artifact_path: ''
